name: Solar System Workflow
#added new uri
env:
  MONGO_URI: ${{vars.MONGO_URI}}
  MONGO_USERNAME: 'waleed'
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: self-hosted
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
 
        - name: Cache NPM dependencies    
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
#          continue-on-error: true instead of this we can use a iff condition on next step by adding a step id
          
        - name: Archive Test Result
          if: failure() && steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step.outcome == 'success'
          # by default a succes() function is running so wwe will use failure () to override that status check 
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
